# Generated by Django 5.1.4 on 2025-01-03 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyfinals',
            old_name='venue',
            new_name='match_venue',
        ),
        migrations.RenameField(
            model_name='historytotalperformance',
            old_name='goals_conceded',
            new_name='draws',
        ),
        migrations.RenameField(
            model_name='historytotalperformance',
            old_name='goals_scored',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='historytotalperformance',
            old_name='matches_draw',
            new_name='matches',
        ),
        migrations.RenameField(
            model_name='historytotalperformance',
            old_name='matches_lost',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='historytotalperformance',
            old_name='matches_won',
            new_name='wins',
        ),
        migrations.RemoveField(
            model_name='historyfinals',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historyfinals',
            name='runner_up',
        ),
        migrations.RemoveField(
            model_name='historyfinals',
            name='score',
        ),
        migrations.RemoveField(
            model_name='historyfinals',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='historytotalperformance',
            name='points',
        ),
        migrations.AddField(
            model_name='historyfinals',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historyfinals',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historyfinals',
            name='match_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historyfinals',
            name='result',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='historyfinals',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
        migrations.AlterField(
            model_name='historytotalperformance',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
